var elementObj = {
1: 'Waterstof - H : Hydrogenium',
2: 'Helium - He',
3: 'Lithium - Li: Litium',
4: 'Beryllium - Be',
5: 'Boor - B : Borum',
6: 'Koolstof - C : Carboneum',
7: 'Stikstof - N : Nitrogenium',
8: 'Zuurstof - O : Oxygenium',
9: 'Fluor - F : Fluorum',
10: 'Neon - Ne',
11: 'Natrium - Na',
12: 'Magnesium - Mg',
13: 'Aluminium - Al',
14: 'Silicium - Si',
15: 'Fosfor - P : Phosphorus',
16: 'Zwavel - S Sulphur',
17: 'Chloor - Cl: Chlorum',
18: 'Argon - Ar',
19: 'Kalium - K',
20: 'Calcium - Ca',
21: 'Scandium - Sc',
22: 'Titanium - Ti',
23: 'Vanadium - V',
24: 'Chroom - Cr',
25: 'Mangaan - Mn : Manganium',
26: 'IJzer - Fe : Ferrum',
27: 'Cobalt - Co: Cobaltum',
28: 'Nikkel - Ni : Niccolum',
29: 'Koper - Cu : Cuprum',
30: 'Zink - Zn : Zincum',
31: 'Gallium - Ga',
32: 'Germanium - Ge',
33: 'Arsenicum - As',
34: 'Seleen - Se',
35: 'Broom - Br : Bromum',
36: 'Krypton - Kr',
37: 'Rubidium - Rb',
38: 'Strontium - Sr',
39: 'Yttrium - Y',
40: 'Zirkonium - Zr',
41: 'Niobium - Nb',
42: 'Molybdeen - Mo : Mo;ybdaenum',
43: 'Technetium - Tc',
44: 'Ruthenium - Ru',
45: 'Rhodium - Rh',
46: 'Palladium - Pd',
47: 'Zilver - Ag : Argentum',
48: 'Cadmium - Cd',
49: 'Indium - In',
50: 'Tin - Sn : Stannum',
51: 'Antimoon - Sb : Stibium',
52: 'Telluur - Te : Tellurium',
53: 'Jodium - I : Iodium',
54: 'Xenon - Xe',
55: 'Caesium - Cs',
56: 'Barium - Ba',
57: 'Lanthanium - La',
58: 'Cerium - Ce',
59: 'Praseodymium - Pr',
60: 'Neodymium - Nd',
61: 'Promethium - Pm',
62: 'Samarium - Sm',
63: 'Europium - Eu',
64: 'Gadolinium - Gd',
65: 'Terbium - Tb',
66: 'Dysprosium - Dy',
67: 'Holmium - Ho',
68: 'Erbium - Er',
69: 'Thulium - Tm',
70: 'Ytterbium - Yb',
71: 'Lutetium - Lu',
72: 'Hafnium - Hf',
73: 'Tantalium - Ta',
74: 'Wolfraam - W : Wolframium',
75: 'Renium - Re',
76: 'Osmium - Os',
77: 'Iridium - Ir',
78: 'Platina - Pt',
79: 'Goud - Au : Aurum',
80: 'Kwik - Hg Hydrargyrum',
81: 'Thallium - Tl',
82: 'Lood - Pb : Plumbum',
83: 'Bismut - Bi : Bismuthum',
84: 'Polonium - Po',
85: 'Astaat - At : Astatium',
86: 'Radon - Rn',
87: 'Francium - Fr',
88: 'Radium - Ra',
89: 'Actinium - Ac',
90: 'Thorium - Th',
91: 'Protactinium - Pa',
92: 'Uranium - U',
93: 'Neptunium - Np',
94: 'Plutonium - Pu',
95: 'Americium - Am',
96: 'Curium - Cm',
97: 'Berkelium - Bk',
98: 'Californium - Cf',
99: 'Einsteinium - Es',
100: 'Fermium - Fm',
101: 'Mendelevium - Md',
102: 'Nobelium - No',
103: 'Lawrencium - Lr',
104: 'Rutherfordium - Rf',
105: 'Dubnium - Db',
106: 'Seaborgium - Sg',
107: 'Bohrium - Bh',
108: 'Hassium - Hs',
109: 'Meitnerium - Mt',
110: 'Darmstadtium - Ds',
111: 'Roentgenium - Rg',
112: 'Copernicium - Cn',
113: 'Nithonium - Nh : (ununtrium)',
114: 'Flerovium - Fl',
115: 'Moscovium - Mc : (ununpentium)',
116: 'Livermorium - Lv',
117: 'Tennessine - Ts : (ununseptium)',
118: 'Organesson - Og : (ununoctium)'}